Ejb AccessTimeOutException when Rules taking long to evaluate messages.
UnionVMS/UVMS-Docker pull request #67
Opened 2018-02-02 16:49 UTC by ankovi

Ejb AccessTimeOutException when Rules taking long to evaluate messages.
Corrected those parameters.

2018-02-03 14:15 UTC, ebrygg requested changes
Oh, if we have code that needs those kind of timeouts then I would suggest that something is seriously wrong. It implies that one of your rules takes a very long time to execute. If that is somehow ok then please use @AccessTimeout on that specific singleton to set the timeout.

2018-02-05 09:49 UTC, ankovi commented
Hi Andreas,
As a matter of fact it was done like that but I thing Wildfly has a bug related to this cause @AccessTimeOut on method/class level is getting somehow overriden by the system-wise setting!

2018-02-13 11:02 UTC, ebrygg commented
ok, we increase this for now, @ankovi will document why this is needed so this can be adressed soon.

2018-02-13 11:02 UTC, ebrygg approved these changes

2018-02-13 12:56 UTC, merged